const String USER_PHONE = "USER_PHONE";
const String USER_NAME = "USER_NAME";
const String DEVICE_TOKEN = "DEVICE_TOKEN";
const String AUTHENTICATION_TOKEN = "auth-token";
const String LOGED_USER_PHONE = "00237456478407";
const String SUM_TRANSFER_SENT = "SUM_TRANSFER_SENT";
const String SUM_TRANSFER_RECEIVED = "SUM_TRANSFER_RECEIVED";
