const String USER = "USER";
const String USER_PHONE = "USER_PHONE";
const String USER_NAME = "USER_NAME";
const String DEVICE_TOKEN = "DEVICE_TOKEN";
const String AUTHORIZATION_TOKEN = "Authorization";
const String CONTENT_TYPE = "Content-Type";
const String APPLICATION_JSON = "application/json";
const String TOKEN_PREFIX = "Bearer ";
const String SUM_TRANSFER_SENT = "SUM_TRANSFER_SENT";
const String SUM_TRANSFER_RECEIVED = "SUM_TRANSFER_RECEIVED";
const String LOGEDIN = "LOGEDIN";
const String YES = "YES";
const String NO = "NO";
const String EPOSSA_EMAIL = "kmer.epossa@gmail.com";
const SITE_WEB = "https://www.kmerconsulting.com/";
const PRIVACY_POLICY_URL =
    "https://kmersoftdesign.wordpress.com/datenschutzerklarung/";
const APP_URL =
    "https://play.google.com/store/apps/details?id=com.kmerconsulting.epossa_app";
